name: ci on pull request

permissions:
  contents: read

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20

    - run: npm ci

    - name: Install vsce
      run: npm install --global @vscode/vsce

    - run: vsce package
