name: VSCE

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - id: package
      name: Package VS Code extension
      uses: nhedger/package-vscode-extension@v1

    - name: Publish VS Code extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: z80-asm-meter-nightly
        path: ${{ steps.package.outputs.packagePath }}
