name: vsce package

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install the dependencies
      run: npm install

    - name: Install vsce
      run: npm install --global @vscode/vsce

    - run: vsce package
